[2021-10-29 18:51:00,008] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash.task_example_id_2 scheduled__2021-10-29T18:03:00+00:00 [queued]>
[2021-10-29 18:51:00,034] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash.task_example_id_2 scheduled__2021-10-29T18:03:00+00:00 [queued]>
[2021-10-29 18:51:00,034] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-29 18:51:00,034] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-29 18:51:00,034] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-29 18:51:00,067] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): task_example_id_2> on 2021-10-29 18:03:00+00:00
[2021-10-29 18:51:00,077] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_bash', 'task_example_id_2', 'scheduled__2021-10-29T18:03:00+00:00', '--job-id', '1245', '--raw', '--subdir', 'DAGS_FOLDER/example_bash.py', '--cfg-path', '/tmp/tmpg3ws_6l7', '--error-file', '/tmp/tmpxw7m3gm8']
[2021-10-29 18:51:00,078] {standard_task_runner.py:77} INFO - Job 1245: Subtask task_example_id_2
[2021-10-29 18:51:00,073] {standard_task_runner.py:52} INFO - Started process 4079 to run task
[2021-10-29 18:51:00,151] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash.task_example_id_2 scheduled__2021-10-29T18:03:00+00:00 [running]> on host 85d7243ef68d
[2021-10-29 18:51:00,278] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash
AIRFLOW_CTX_TASK_ID=task_example_id_2
AIRFLOW_CTX_EXECUTION_DATE=2021-10-29T18:03:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-29T18:03:00+00:00
[2021-10-29 18:51:00,281] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-29 18:51:00,282] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "This is a bash test bro 2"']
[2021-10-29 18:51:00,305] {subprocess.py:85} INFO - Output:
[2021-10-29 18:51:00,319] {subprocess.py:89} INFO - This is a bash test bro 2
[2021-10-29 18:51:00,319] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-29 18:51:00,445] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=example_bash, task_id=task_example_id_2, execution_date=20211029T180300, start_date=20211029T185100, end_date=20211029T185100
[2021-10-29 18:51:00,521] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-29 18:51:00,579] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
